### ISSUE TITLE
高血压自动化-ACMG条目的修改

### ISSUE THREAD

**Issue by lijingjing-1** [nuohexinkang/test-project#35]
![image](https://user-images.githubusercontent.com/49857164/57516647-b77ff780-7347-11e9-9da8-9412f9957f6a.png)
 PM5 ，为了保证准确，去掉 HGMD数据库的DM对应，只保留clinvar的比对，辛苦修改，谢谢

**Comment by panqi113** [comment]
已去掉。190513-16:21修改。
