### ISSUE TITLE
3782样本中的CACNA1C基因的变异，cds没有按照正常格式出现，是这样的c.G5599A

### ISSUE THREAD

**Issue by xiaoqingsun** [nuohexinkang/test-project#5]
3782样本中的CACNA1C基因的变异，cds没有按照正常格式出现，是这样的c.G5599A

**Comment by xiaoqingsun** [comment]
脚本已经修改好

**Comment by lijingjing-1** [comment]
![image](https://user-images.githubusercontent.com/49857164/56951800-497b4980-6b6b-11e9-834b-9abb751b9618.png)
3915样本重复出现了
