### ISSUE TITLE
低质量序列质控

### ISSUE THREAD

**Issue by wangguoxx** [nuohexinkang/test-project#8]
![image](https://user-images.githubusercontent.com/49855793/56707195-759d6180-674a-11e9-93b1-70c0ceff377f.png)
N003753  14     23859426         23859430         GCAGT     -        exonic       MYH6       .        frameshift deletion 
这个变异附近的序列都是白色的reads，可以比对到多个地方，是质量很差的变异，是不是应该过滤掉。
如果是SNV变异，我们不看IGV文件是不能发现这样的问题的。

**Comment by xiaoqingsun** [comment]
IGV用的是原始的全部reads比对的bam文件，所以低质量的会有显示。实际生产过程中，会把低质量的reads进行过滤。

**Comment by wangguoxx** [comment]
OK，明白了，谢谢小庆

**Comment by xiaoqingsun** [comment]
You are welcome
